## 1

### Logical operators

In [1]:
print(1 == 0)    # 1 equals 0
print(1 == 1)    # 1 equals 1
print(1 != 0)    # 1 is not equal to 0
print(5 >= 5)    # 5 is greater than or equal to 5
print(5 >= 6)    # 5 is greater than or equal to 6
print(2 > 1 and 3 > 2)
print(2 > 1 and 3 < 2)
print(2 > 1 or  3 < 2)
print(2 < 1 and 3 < 2)

False
True
True
True
False
True
False
True
False


### bitwise operators

In [2]:
print(1 << 2) # 00001 -> 00100
print(1 << 4) # 00001 -> 10000
print(4 >> 1) # 00100 -> 00010

4
16
2


### some for loop techniques

In [3]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print(new_list) # print new_list

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [4]:
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25]


### list comprehension

In [5]:
foo = [1,2,3,4,5]
squares = [x**2 for x in foo] 
print(squares)

[1, 4, 9, 16, 25]


In [6]:
print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]


# Functions

In [7]:
def product(x,y):
    return x*y

def say_hi():
    print("Welcome to QuantConnect")
print(product(3,4))
say_hi()

12
Welcome to QuantConnect


### Built-in Function

In [8]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print(k + 1, tickers[k])

The number of tickers is 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE


### lambda

In [10]:
f = lambda x: x**2
g = lambda x,y:x+y
print(f(3), g(4,6))

9 10


### map

In [11]:
print(list(map(f, range(10))))
print(list(map(g, range(10), range(3,13))))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[3, 5, 7, 9, 11, 13, 15, 17, 19, 21]


### sorted

In [12]:
print(sorted([5,2,3,4,1]))

[1, 2, 3, 4, 5]


In [13]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
print(sorted(price_list, key = lambda x: x[1]))

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


In [14]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print(price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


### Object-Oriented Programming

In [15]:
class Stock:
    def __init__(self, ticker, open_, close, volume):
        self.ticker = ticker
        self.open = open_
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open_ - 1

    def update(self, open_, close):
        self.open = open_
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print(self.rate_return)

In [16]:
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)

In [17]:
print(apple.ticker)
print(google.ticker)
apple.print_return()

AAPL
GOOGL
0.0027837706173012844


### class inheritance

In [18]:
class Child(Stock):
    def __init__(self, name):
        self.name = name

In [19]:
aa = Child('AA')

In [20]:
aa.update(100, 102)
aa.open

100

## numpy

In [21]:
import numpy as np

### basic numpy arrays

In [22]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [23]:
Ar = np.array([[1,3], [2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [24]:
print(Ar.shape)

(2, 2)


In [25]:
print('First column:', Ar[:,0])
print('First row:', Ar[0,:])

First column: [1 2]
First row: [1 3]


### Functions for array

In [26]:
print(np.log(price_array))
print(np.sin(price_array))

[4.96793654 4.98244156 4.9675886  4.96995218 4.96633504 4.96018375]
[-0.70559472  0.96790038 -0.74012893 -0.47350161 -0.8485623  -0.94845689]


### some Statistic

In [27]:
print(np.mean(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
863.38
145.83


## pandas

In [28]:
import pandas as pd

### pandas.series

In [29]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print(s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [30]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [31]:
s.index = [6,5,4,3,2,1]
print(s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [32]:
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


### We can get the statistical summaries of a series

In [33]:
s = pd.Series(price, name = 'Apple Prices')
print(s)
print(s.describe())

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


### Time index

In [34]:
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print(time_index)
s.index = time_index

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')


In [35]:
print(s)

2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [36]:
print(s.iloc[2], s['2017-01-03 '])

143.68 143.68


In [37]:
print(s['2017-01-03' : '2017-01-05'])

2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [38]:
s < np.mean(s)

2017-01-01     True
2017-01-02    False
2017-01-03     True
2017-01-04    False
2017-01-05     True
2017-01-06     True
Freq: D, Name: Apple Prices, dtype: bool

## Rate of Return

$$
r = \frac{p_t}{p_0} - 1 = \frac{p_t - p_0}{p_0}
$$

In [39]:
import numpy as np
rate_return = 102.0/100 - 1
print(rate_return)

0.020000000000000018


let's say the series of return is :
$$
\mathbf{r} = \{r_1, r_2, r_3, ..\}
$$
cumulative return or overall return can be calculated by 
$$
r = \Pi_i(1+r_i) -1
$$

Now consider the following situation: we have two strategies: strategy A and strategy B. 

We backtested strategy A for 1 years and the cumulative return is 20%, while we backtested strategy B for 3 months(one quarter) and the cumulative return is 6%. 

Which strategy has a high rate of return?

Our commonly used method is to convert all the returns into compounding annual return, regardless of the investing horizon of each strategy.

$$
(1+0.06)^4 - 1 = r\\
r = 0.262
$$

## Logarithm Return

### Nominal return
In the above example, strategy A has $6%$ return over three months. Nominally, the annual return would be $4*6%$ = 24%. This nominal annual interest rate is called the **stated annual interest rate**.

It is calculated as the periodic interest rate times (6%) the number of periods per year (4). 

It works according to the simple interest and does not take into account the compounding periods, while the effective annual interest rate is around **26%** as we calculated above and it does account for **intra-year compounding**.
$$
r_{\mathcal{effective}} = (1 + \frac{r_\mathcal{nominal}}{n})^n - 1
$$

Now imagine the price of asset is changing every second or even every millisecond, the period of compounding n approaches infinite. This is called **continuous compounding**. The calculation formula is given below:

$$
\lim_{n \to +\infty}(1+\frac{r}{n})^n = e^r
$$

Therefore, 
$$
e^{r_\mathcal{nominal}} = 1 + r_{\mathcal{effective}} = \frac{p_t}{p_0}
$$ 
then, we take $ln$ on both side of the equation:
$$
r_\mathcal{nominal} = lnp_t - lnp_0
$$
Here we got the **logarithmic return**, or **continuously compounded return**.
if $r_\mathcal{nominal} \ll 1$, then, $r_\mathcal{effective} = r_\mathcal{nominal}$


In [44]:
import quandl
import numpy as np
import quandl
quandl.ApiConfig.api_key = 'SAfniVERzMmdSb_d1zw8'
#get quandl data
aapl_table = quandl.get('WIKI/AAPL')
aapl = aapl_table.loc['2017-3',['Open','Close']]
#take log return
aapl['log_price'] = np.log(aapl.Close)
aapl['log_return'] = aapl['log_price'].diff()
print(aapl)

               Open   Close  log_price  log_return
Date                                              
2017-03-01  137.890  139.79   4.940141         NaN
2017-03-02  140.000  138.96   4.934186   -0.005955
2017-03-03  138.780  139.78   4.940070    0.005884
2017-03-06  139.365  139.34   4.936917   -0.003153
2017-03-07  139.060  139.52   4.938208    0.001291
2017-03-08  138.950  139.00   4.934474   -0.003734
2017-03-09  138.740  138.68   4.932169   -0.002305
2017-03-10  139.250  139.14   4.935481    0.003311
2017-03-13  138.850  139.20   4.935912    0.000431
2017-03-14  139.300  138.99   4.934402   -0.001510
2017-03-15  139.410  140.46   4.944923    0.010521
2017-03-16  140.720  140.69   4.946559    0.001636
2017-03-17  141.000  139.99   4.941571   -0.004988
2017-03-20  140.400  141.46   4.952017    0.010446
2017-03-21  142.110  139.84   4.940499   -0.011518
2017-03-22  139.845  141.42   4.951734    0.011235
2017-03-23  141.260  140.92   4.948192   -0.003542
2017-03-24  141.500  140.64   4

In [42]:
help(quandl.get)

Help on function get in module quandl.get:

get(dataset, **kwargs)
    Return dataframe of requested dataset from Quandl.
    :param dataset: str or list, depending on single dataset usage or multiset usage
            Dataset codes are available on the Quandl website
    :param str api_key: Downloads are limited to 50 unless api_key is specified
    :param str start_date, end_date: Optional datefilers, otherwise entire
           dataset is returned
    :param str collapse: Options are daily, weekly, monthly, quarterly, annual
    :param str transform: options are diff, rdiff, cumul, and normalize
    :param int rows: Number of rows which will be returned
    :param str order: options are asc, desc. Default: `asc`
    :param str returns: specify what format you wish your dataset returned as,
        either `numpy` for a numpy ndarray or `pandas`. Default: `pandas`
    :returns: :class:`pandas.DataFrame` or :class:`numpy.ndarray`
    Note that Pandas expects timeseries data to be sorte

In [41]:
aapl_table

Open    High     Low    Close      Volume  Ex-Dividend  \
Date                                                                   
1980-12-12   28.75   28.87   28.75   28.750   2093900.0          0.0   
1980-12-15   27.38   27.38   27.25   27.250    785200.0          0.0   
1980-12-16   25.37   25.37   25.25   25.250    472000.0          0.0   
1980-12-17   25.87   26.00   25.87   25.870    385900.0          0.0   
1980-12-18   26.63   26.75   26.63   26.630    327900.0          0.0   
...            ...     ...     ...      ...         ...          ...   
2018-03-21  175.04  175.09  171.26  171.270  35247358.0          0.0   
2018-03-22  170.00  172.68  168.60  168.845  41051076.0          0.0   
2018-03-23  168.39  169.92  164.94  164.940  40248954.0          0.0   
2018-03-26  168.07  173.10  166.44  172.770  36272617.0          0.0   
2018-03-27  173.68  175.15  166.92  168.340  38962839.0          0.0   

            Split Ratio   Adj. Open   Adj. High    Adj. Low  Adj. Close  \
Date                                                                      
1980-12-12          1.0    0.422706    0.424470    0.422706    0.422706   
1980-12-15          1.0    0.402563    0.402563    0.400652    0.400652   
1980-12-16          1.0    0.373010    0.373010    0.371246    0.371246   
1980-12-17          1.0    0.380362    0.382273    0.380362    0.380362   
1980-12-18          1.0    0.391536    0.393300    0.391536    0.391536   
...                 ...         ...         ...         ...         ...   
2018-03-21          1.0  175.040000  175.090000  171.260000  171.270000   
2018-03-22          1.0  170.000000  172.680000  168.600000  168.845000   
2018-03-23          1.0  168.390000  169.920000  164.940000  164.940000   
2018-03-26          1.0  168.070000  173.100000  166.440000  172.770000   
2018-03-27          1.0  173.680000  175.150000  166.920000  168.340000   

            Adj. Volume  
Date                     
1980-12-12  117258400.0  
1980-12-15   43971200.0  
1980-12-16   26432000.0  
1980-12-17   21610400.0  
1980-12-18   18362400.0  
...                 ...  
2018-03-21   35247358.0  
2018-03-22   41051076.0  
2018-03-23   40248954.0  
2018-03-26   36272617.0  
2018-03-27   38962839.0  

[9400 rows x 12 columns]